export const blank = {
  key: "blank",
  title: "Samantha Fab — Campaign Hero",
  eyebrow: "Playground / Campaign hero",
  description:
    "A full-bleed campaign hero with replaceable slides, centered messaging, and a direct route into the collection.",
  sections: [
    {
      id: "design-usp-strip",
      number: "00",
      name: "USP Strip",
      type: "usp-strip",
      hideReviewNotes: true,
      annotation: "One promise at a time — icon + label, cycling every three seconds.",
      items: [
        { icon: "truck", label: "COD across India" },
        { icon: "refresh", label: "Easy returns & exchange" },
        { icon: "chat", label: "WhatsApp assistance" },
      ],
    },
    {
      id: "design-utility-navigation",
      number: "00b",
      name: "Navigation",
      type: "header",
      hideReviewNotes: true,
      annotation:
        "Keep the navigation separate from the campaign canvas so the hero can stay completely image-led.",
      brand: "SAMANTHA FAB",
      nav: [
        { label: "Shop", href: "/?route=shop" },
        { label: "Collections", href: "/?route=collections" },
        { label: "Discover", href: "/?route=discover" },
        { label: "Services", href: "/?route=services" },
      ],
      actions: [
        { label: "Search", href: "/?route=search", ariaLabel: "Search" },
        { label: "Account", href: "/?route=account", ariaLabel: "Account", className: "nav-action--account" },
        { label: "Bag (0)", href: "/?route=bag", ariaLabel: "Bag, 0 items" },
      ],
    },
    {
      id: "design-campaign-hero",
      number: "01",
      name: "Campaign Hero",
      type: "campaign-hero",
      interval: 7000,
      annotation:
        "One dominant image, one centered message, and one clear action. Campaign imagery and copy can be replaced in this data object without changing the layout.",
      slides: [
        {
          eyebrow: "New collection / 2026",
          title: "The art of becoming.",
          copy: "Statement sarees for evenings that deserve to be remembered.",
          primaryAction: { label: "Shop Now", href: "/?route=new-edit" },
          media: {
            src: "/assets/design-hero-terracotta.png",
            alt: "Indian woman in a rose and wine saree standing in a terracotta interior",
            tone: "indigo",
            position: "center center",
            note: "Generated campaign image — replace with final Samantha Fab campaign photography.",
          },
        },
        {
          eyebrow: "The festive edit",
          title: "Made for your moment.",
          copy: "Drapes with colour, ease, and a little more occasion.",
          primaryAction: { label: "Shop Now", href: "/?route=festive" },
          media: {
            src: "/assets/design-hero-ivory-arch.png",
            alt: "Indian woman in an ivory and gold saree beneath a deep blue-green stone arch",
            tone: "ochre",
            position: "center center",
            note: "Generated campaign image — replace with final Samantha Fab campaign photography.",
          },
        },
        {
          eyebrow: "Everyday, reimagined",
          title: "Wear the feeling.",
          copy: "Soft movement and expressive prints for all your in-between hours.",
          primaryAction: { label: "Shop Now", href: "/?route=everyday" },
          media: {
            src: "/assets/design-hero-magenta-garden.png",
            alt: "Indian woman in a magenta and green saree seated in a shadowed botanical courtyard",
            tone: "moss",
            position: "center center",
            note: "Generated campaign image — replace with final Samantha Fab campaign photography.",
          },
        },
      ],
    },
    {
      id: "design-shop-by-collection",
      number: "02",
      name: "Shop by Collection",
      type: "collection-bento",
      title: "Shop by collection",
      copy: "Start with the moment. The saree follows.",
      hideReviewNotes: true,
      annotation: "Edge-to-edge 2+3 occasion bento. Image fill, bottom scrim, bottom-left labels.",
      items: [
        {
          title: "Everyday",
          copy: "Starting with ₹1,299",
          href: "/?route=occasion-everyday",
          media: {
            src: "/assets/collection-everyday-editorial.png",
            alt: "Woman in a printed saree moving through a sunlit heritage courtyard",
            tone: "ochre",
            position: "center top",
          },
        },
        {
          title: "Work",
          copy: "Starting with ₹1,899",
          href: "/?route=occasion-work",
          media: {
            src: "/assets/collection-work-editorial.png",
            alt: "Woman in an indigo and olive handloom saree in a textile studio",
            tone: "indigo",
            position: "center top",
          },
        },
        {
          title: "Festive",
          copy: "Starting with ₹1,999",
          href: "/?route=occasion-festive",
          media: {
            src: "/assets/collection-festive-editorial.png",
            alt: "Woman arranging a marigold garland in a rust silk saree",
            tone: "rust",
            position: "center center",
          },
        },
        {
          title: "Wedding",
          copy: "Starting with ₹2,499",
          href: "/?route=occasion-wedding",
          media: {
            src: "/assets/collection-wedding-editorial.png",
            alt: "Woman adjusting a plum silk saree in a heritage interior",
            tone: "moss",
            position: "center center",
          },
        },
        {
          title: "Ready-to-wear",
          copy: "Starting with ₹1,699",
          href: "/?route=occasion-rtw",
          media: {
            src: "/assets/collection-ready-to-wear-editorial.png",
            alt: "Woman walking through a gallery in a modern ready-to-wear saree",
            tone: "paper",
            position: "center center",
          },
        },
      ],
    },
    {
      id: "design-new-arrivals",
      number: "03",
      name: "New Arrivals",
      type: "product-carousel",
      hideReviewNotes: true,
      eyebrow: "Just in",
      title: "New arrivals",
      copy: "Fresh drapes and easy pieces, newly in the studio.",
      viewAll: { label: "View all", href: "/?route=new-arrivals" },
      products: [
        {
          name: "Sage green handblock saree",
          material: "Handblock cotton",
          price: "₹1,899",
          href: "/?route=product-sage-handblock",
          tag: "New",
          media: {
            src: "/assets/product-sage.jpg",
            alt: "Sage green saree with geometric weave",
            tone: "moss",
            position: "center",
          },
        },
        {
          name: "Indigo stripe ready-to-wear",
          material: "Soft linen blend",
          price: "₹2,499",
          href: "/?route=product-indigo-rtw",
          tag: "New",
          media: {
            src: "/assets/product-indigo.jpg",
            alt: "Indigo striped ready-to-wear saree",
            tone: "indigo",
            position: "center",
          },
        },
        {
          name: "Marigold printed saree",
          material: "Lightweight georgette",
          price: "₹1,299",
          href: "/?route=product-marigold",
          tag: "New",
          media: {
            src: "/assets/product-marigold.jpg",
            alt: "Marigold printed saree",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Black border everyday saree",
          material: "Everyday cotton",
          price: "₹1,699",
          href: "/?route=product-black-border",
          tag: "New",
          media: {
            src: "/assets/product-black.jpg",
            alt: "Pink and black bordered saree",
            tone: "ink",
            position: "center",
          },
        },
        {
          name: "Printed courtyard saree",
          material: "Soft handloom cotton",
          price: "₹1,599",
          href: "/?route=product-courtyard-print",
          media: {
            src: "/assets/occasion-everyday.jpg",
            alt: "Printed saree styled for an everyday wardrobe",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Indigo workroom saree",
          material: "Handloom silk cotton",
          price: "₹2,199",
          href: "/?route=product-workroom-indigo",
          media: {
            src: "/assets/occasion-work.jpg",
            alt: "Indigo and olive saree in a workroom",
            tone: "indigo",
            position: "center",
          },
        },
        {
          name: "Rust marigold silk saree",
          material: "Silk blend",
          price: "₹2,699",
          href: "/?route=product-rust-marigold",
          media: {
            src: "/assets/occasion-festive.jpg",
            alt: "Rust silk saree with marigold garlands",
            tone: "rust",
            position: "center",
          },
        },
        {
          name: "Coral easy-drape saree",
          material: "Lightweight organza",
          price: "₹2,399",
          href: "/?route=product-coral-drape",
          media: {
            src: "/assets/occasion-rtw.jpg",
            alt: "Coral ready-to-wear saree in a modern interior",
            tone: "paper",
            position: "center",
          },
        },
      ],
    },
    {
      id: "design-ready-to-wear-banner",
      number: "04",
      name: "Ready to Wear Banner",
      type: "feature-banner",
      hideReviewNotes: true,
      eyebrow: "The drape, made easy",
      title: "Ready to wear",
      copy: "Pre-stitched sarees with pockets — easy on, easy all day.",
      action: { label: "Shop ready-to-wear", href: "/?route=ready-to-wear" },
      media: [
        {
          src: "/assets/collection-ready-to-wear-editorial.png",
          alt: "Woman walking through a gallery in a modern ready-to-wear saree",
          tone: "paper",
          position: "center top",
        },
        {
          src: "/assets/design-hero-terracotta.png",
          alt: "Detail of a draped saree in a warm studio setting",
          tone: "ochre",
          position: "center center",
        },
        {
          src: "/assets/collection-everyday-editorial.png",
          alt: "Woman in a printed saree moving through a sunlit courtyard",
          tone: "ochre",
          position: "center top",
        },
        {
          src: "/assets/collection-festive-editorial.png",
          alt: "Woman arranging a marigold garland in a rust silk saree",
          tone: "rust",
          position: "center center",
        },
      ],
    },
    {
      id: "footer",
      number: "05",
      name: "Footer",
      type: "footer",
      annotation:
        "Close the trust loop with shipping, returns, COD, WhatsApp, care and contact details.",
      brand: "SAMANTHA FAB",
      brandLine: "Modern drapes, expressive prints and everyday ease.",
      columns: [
        {
          heading: "Shop",
          links: [
            { label: "New arrivals", href: "/?route=new-arrivals" },
            { label: "Sarees", href: "/?route=sarees" },
            { label: "Ready-to-wear", href: "/?route=ready-to-wear" },
            { label: "Sale", href: "/?route=sale" },
          ],
        },
        {
          heading: "Help",
          links: [
            { label: "Shipping", href: "/?route=shipping" },
            { label: "Returns", href: "/?route=returns" },
            { label: "COD", href: "/?route=cod" },
            { label: "Care guide", href: "/?route=care" },
          ],
        },
        {
          heading: "About",
          links: [
            { label: "Our story", href: "/?route=story" },
            { label: "Journal", href: "/?route=journal" },
            { label: "Contact", href: "/?route=contact" },
          ],
        },
        {
          heading: "Stay in touch",
          links: [
            { label: "Instagram", href: "/?route=instagram" },
            { label: "WhatsApp", href: "https://wa.me/" },
            { label: "Email", href: "mailto:hello@samanthafab.example" },
          ],
        },
      ],
      copyright: "© Samantha Fab. Playground concept.",
    },
  ],
};
