export const blank = {
  key: "blank",
  title: "Samantha Fab — Campaign Hero",
  eyebrow: "Playground / Campaign hero",
  description:
    "A full-bleed campaign hero with replaceable slides, centered messaging, and a direct route into the collection.",
  sections: [
    {
      id: "design-usp-strip",
      number: "00",
      name: "USP Strip",
      type: "usp-strip",
      hideReviewNotes: true,
      annotation: "One promise at a time — icon + label, cycling every three seconds.",
      items: [
        { icon: "truck", label: "COD across India" },
        { icon: "refresh", label: "Easy returns & exchange" },
        { icon: "chat", label: "WhatsApp assistance" },
      ],
    },
    {
      id: "design-utility-navigation",
      number: "00b",
      name: "Navigation",
      type: "header",
      hideReviewNotes: true,
      annotation:
        "Keep the navigation separate from the campaign canvas so the hero can stay completely image-led.",
      brand: "SAMANTHA FAB",
      nav: [
        { label: "Shop", href: "/?route=shop" },
        { label: "Collections", href: "/?route=collections" },
        { label: "Discover", href: "/?route=discover" },
        { label: "Services", href: "/?route=services" },
      ],
      actions: [
        { label: "Search", href: "/?route=search", ariaLabel: "Search" },
        { label: "Account", href: "/?route=account", ariaLabel: "Account", className: "nav-action--account" },
        { label: "Bag (0)", href: "/?route=bag", ariaLabel: "Bag, 0 items" },
      ],
    },
    {
      id: "design-campaign-hero",
      number: "01",
      name: "Campaign Hero",
      type: "campaign-hero",
      interval: 7000,
      annotation:
        "One dominant image, one centered message, and one clear action. Campaign imagery and copy can be replaced in this data object without changing the layout.",
      slides: [
        {
          eyebrow: "New collection / 2026",
          title: "The art of becoming.",
          copy: "Statement sarees for evenings that deserve to be remembered.",
          primaryAction: { label: "Shop Now", href: "/?route=new-edit" },
          media: {
            src: "/assets/design-campaign-hero-green.jpg",
            alt: "Indian woman in a dark teal saree with a flying sheer pallu in a warm peach arch",
            tone: "moss",
            position: "center center",
            note: "Curated archive image from SAVE.zip — selected as the campaign anchor for movement, contrast, and warm architecture.",
          },
        },
        {
          eyebrow: "The festive edit",
          title: "Made for your moment.",
          copy: "Drapes with colour, ease, and a little more occasion.",
          primaryAction: { label: "Shop Now", href: "/?route=festive" },
          media: {
            src: "/assets/design-story-cream.jpg",
            alt: "Indian woman in a cream floral saree holding flowers in a warm lived-in interior",
            tone: "rust",
            position: "center center",
            note: "Curated archive image from SAVE.zip — selected for the softer, lived-in side of the collection.",
          },
        },
        {
          eyebrow: "Everyday, reimagined",
          title: "Wear the feeling.",
          copy: "Soft movement and expressive prints for all your in-between hours.",
          primaryAction: { label: "Shop Now", href: "/?route=everyday" },
          media: {
            src: "/assets/design-campaign-hero-red.jpg",
            alt: "Indian woman in a red and marigold saree standing in a clean studio setting",
            tone: "rust",
            position: "center center",
            note: "Curated archive image from SAVE.zip — selected for a clear festive colour hit in the hero rotation.",
          },
        },
      ],
    },
    {
      id: "design-shop-by-collection",
      number: "02",
      name: "Shop by Collection",
      type: "collection-bento",
      title: "Shop by collection",
      copy: "Start with the moment. The saree follows.",
      hideReviewNotes: true,
      annotation: "Edge-to-edge 2+3 occasion bento. Image fill, bottom scrim, bottom-left labels.",
      items: [
        {
          title: "Everyday",
          copy: "Starting with ₹1,299",
          href: "/?route=occasion-everyday",
          media: {
            src: "/assets/design-collection-everyday.jpg",
            alt: "Woman in a pale printed saree seated in a warm sunlit room",
            tone: "ochre",
            position: "center top",
          },
        },
        {
          title: "Work",
          copy: "Starting with ₹1,899",
          href: "/?route=occasion-work",
          media: {
            src: "/assets/design-collection-work.jpg",
            alt: "Woman in a cream, black, and maroon graphic saree in a clean studio",
            tone: "rust",
            position: "center top",
          },
        },
        {
          title: "Festive",
          copy: "Starting with ₹1,999",
          href: "/?route=occasion-festive",
          media: {
            src: "/assets/design-collection-festive.jpg",
            alt: "Woman in a vivid red and marigold saree in a clean studio",
            tone: "rust",
            position: "center top",
          },
        },
        {
          title: "Wedding",
          copy: "Starting with ₹2,499",
          href: "/?route=occasion-wedding",
          media: {
            src: "/assets/design-collection-wedding.jpg",
            alt: "Woman in a dark teal and gold saree seated against heritage architecture",
            tone: "moss",
            position: "center center",
          },
        },
        {
          title: "Ready-to-wear",
          copy: "Starting with ₹1,699",
          href: "/?route=occasion-rtw",
          media: {
            src: "/assets/design-collection-ready-to-wear.jpg",
            alt: "Woman sweeping a pastel striped saree through a clean studio",
            tone: "paper",
            position: "center center",
          },
        },
      ],
    },
    {
      id: "design-new-arrivals",
      number: "03",
      name: "New Arrivals",
      type: "product-carousel",
      hideReviewNotes: true,
      title: "New arrivals",
      copy: "Fresh drapes and easy pieces, newly in the studio.",
      viewAll: { label: "View all", href: "/?route=new-arrivals" },
      products: [
        {
          name: "Sage green handblock saree",
          material: "Handblock cotton",
          price: "₹1,899",
          compareAt: "₹2,299",
          href: "/?route=product-sage-handblock",
          tag: "Everyday",
          media: {
            src: "/assets/design-product-sage.jpg",
            alt: "Sage green floral saree styled in a clean studio",
            tone: "moss",
            position: "center",
          },
        },
        {
          name: "Indigo stripe ready-to-wear",
          material: "Soft linen blend",
          price: "₹2,499",
          compareAt: "₹2,999",
          href: "/?route=product-indigo-rtw",
          tag: "Ready-to-wear",
          swatches: [
            { color: "#1f3a5f", label: "Indigo" },
            { color: "#c4a574", label: "Sand" },
            { color: "#5c2a3a", label: "Plum" },
          ],
          media: {
            src: "/assets/design-product-indigo.jpg",
            alt: "Indigo and ochre geometric saree with a flowing pallu",
            tone: "indigo",
            position: "center",
          },
        },
        {
          name: "Marigold printed saree",
          material: "Lightweight georgette",
          price: "₹1,299",
          compareAt: "₹1,599",
          href: "/?route=product-marigold",
          tag: "Festive",
          media: {
            src: "/assets/design-product-marigold.jpg",
            alt: "Marigold yellow saree with a green blouse",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Black border everyday saree",
          material: "Everyday cotton",
          price: "₹1,699",
          compareAt: "₹2,099",
          href: "/?route=product-black-border",
          tag: "Everyday",
          media: {
            src: "/assets/design-product-black.jpg",
            alt: "Black and white graphic saree with a bold border",
            tone: "ink",
            position: "center",
          },
        },
        {
          name: "Printed courtyard saree",
          material: "Soft handloom cotton",
          price: "₹1,599",
          compareAt: "₹1,899",
          href: "/?route=product-courtyard-print",
          tag: "Everyday",
          media: {
            src: "/assets/design-collection-everyday.jpg",
            alt: "Pale printed saree styled for an everyday wardrobe",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Indigo workroom saree",
          material: "Handloom silk cotton",
          price: "₹2,199",
          compareAt: "₹2,699",
          href: "/?route=product-workroom-indigo",
          tag: "Work",
          media: {
            src: "/assets/design-collection-work.jpg",
            alt: "Cream, black, and maroon saree styled for work",
            tone: "rust",
            position: "center",
          },
        },
        {
          name: "Rust marigold silk saree",
          material: "Silk blend",
          price: "₹2,699",
          compareAt: "₹3,299",
          href: "/?route=product-rust-marigold",
          tag: "Wedding",
          media: {
            src: "/assets/design-collection-festive.jpg",
            alt: "Red and marigold saree styled for a festive occasion",
            tone: "rust",
            position: "center",
          },
        },
        {
          name: "Coral easy-drape saree",
          material: "Lightweight organza",
          price: "₹2,399",
          compareAt: "₹2,899",
          href: "/?route=product-coral-drape",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-collection-ready-to-wear.jpg",
            alt: "Pastel striped saree styled for ready-to-wear ease",
            tone: "paper",
            position: "center",
          },
        },
      ],
    },
    {
      id: "design-ready-to-wear-banner",
      number: "04",
      name: "Ready to Wear Banner",
      type: "feature-banner",
      hideReviewNotes: true,
      eyebrow: "The drape, made easy",
      title: "Ready to wear",
      copy: "Pre-stitched sarees with pockets — easy on, easy all day.",
      action: { label: "Shop ready-to-wear", href: "/?route=ready-to-wear" },
      media: [
        {
          src: "/assets/design-collection-ready-to-wear.jpg",
          alt: "Woman sweeping a pastel striped saree through a clean studio",
          tone: "paper",
          position: "center top",
        },
        {
          src: "/assets/design-ready-to-wear-detail.jpg",
          alt: "Close-up of a sage textile pocket and floral weave",
          tone: "moss",
          position: "center center",
        },
        {
          src: "/assets/design-campaign-hero-green.jpg",
          alt: "Woman in a dark teal saree with a flying sheer pallu in a warm peach arch",
          tone: "moss",
          position: "center top",
        },
        {
          src: "/assets/design-story-cream.jpg",
          alt: "Woman in a cream floral saree holding flowers in a warm lived-in interior",
          tone: "rust",
          position: "center center",
        },
      ],
    },
    {
      id: "design-ready-to-wear-products",
      number: "05",
      name: "Ready to wear products",
      type: "product-carousel",
      hideReviewNotes: true,
      action: { label: "Shop ready-to-wear", href: "/?route=ready-to-wear" },
      products: [
        {
          name: "Indigo stripe ready-to-wear",
          material: "Soft linen blend",
          price: "₹2,499",
          compareAt: "₹2,999",
          href: "/?route=product-indigo-rtw",
          tag: "Ready-to-wear",
          swatches: [
            { color: "#1f3a5f", label: "Indigo" },
            { color: "#c4a574", label: "Sand" },
            { color: "#5c2a3a", label: "Plum" },
          ],
          media: {
            src: "/assets/design-product-indigo.jpg",
            alt: "Indigo and ochre geometric ready-to-wear saree",
            tone: "indigo",
            position: "center",
          },
        },
        {
          name: "Coral easy-drape saree",
          material: "Lightweight organza",
          price: "₹2,399",
          compareAt: "₹2,899",
          href: "/?route=product-coral-drape",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-product-marigold.jpg",
            alt: "Marigold yellow ready-to-wear saree",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Sage pocket drape",
          material: "Handblock cotton",
          price: "₹1,999",
          compareAt: "₹2,399",
          href: "/?route=product-sage-rtw",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-product-black.jpg",
            alt: "Black and white graphic ready-to-wear saree",
            tone: "ink",
            position: "center",
          },
        },
        {
          name: "Marigold pre-stitched saree",
          material: "Lightweight georgette",
          price: "₹1,799",
          compareAt: "₹2,199",
          href: "/?route=product-marigold-rtw",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-product-sage.jpg",
            alt: "Sage green floral ready-to-wear saree",
            tone: "moss",
            position: "center",
          },
        },
        {
          name: "Black border easy wrap",
          material: "Everyday cotton",
          price: "₹1,899",
          compareAt: "₹2,299",
          href: "/?route=product-black-border-rtw",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-collection-everyday.jpg",
            alt: "Pale printed ready-to-wear saree for everyday wear",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Courtyard print ready-to-wear",
          material: "Soft handloom cotton",
          price: "₹1,699",
          compareAt: "₹1,999",
          href: "/?route=product-courtyard-rtw",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-collection-work.jpg",
            alt: "Cream, black, and maroon ready-to-wear saree",
            tone: "rust",
            position: "center",
          },
        },
        {
          name: "Workroom indigo drape",
          material: "Handloom silk cotton",
          price: "₹2,299",
          compareAt: "₹2,799",
          href: "/?route=product-workroom-rtw",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-collection-festive.jpg",
            alt: "Red and marigold ready-to-wear saree",
            tone: "rust",
            position: "center",
          },
        },
        {
          name: "Rust marigold ready-to-wear",
          material: "Silk blend",
          price: "₹2,799",
          compareAt: "₹3,399",
          href: "/?route=product-rust-rtw",
          tag: "Ready-to-wear",
          media: {
            src: "/assets/design-collection-ready-to-wear.jpg",
            alt: "Pastel striped ready-to-wear saree",
            tone: "paper",
            position: "center",
          },
        },
      ],
    },
    {
      id: "design-shop-under",
      number: "06",
      name: "Shop under",
      type: "shop-under",
      hideReviewNotes: true,
      title: "BEST ON BUDGET",
      items: [
        {
          title: "Shop under",
          price: "₹999",
          href: "/?route=shop-under-999",
          media: {
            src: "/assets/design-product-marigold.jpg",
            alt: "Marigold yellow saree for everyday wear",
            tone: "ochre",
            position: "center top",
          },
        },
        {
          title: "Shop under",
          price: "₹1,999",
          href: "/?route=shop-under-1999",
          media: {
            src: "/assets/design-collection-everyday.jpg",
            alt: "Woman in a pale printed saree in a warm room",
            tone: "ochre",
            position: "center top",
          },
        },
        {
          title: "Shop under",
          price: "₹2,999",
          href: "/?route=shop-under-2999",
          media: {
            src: "/assets/design-collection-festive.jpg",
            alt: "Woman in a red and marigold festive saree",
            tone: "rust",
            position: "center center",
          },
        },
      ],
    },
    {
      id: "design-shop-by-material",
      number: "07",
      name: "Shop by Material",
      type: "material-rail",
      hideReviewNotes: true,
      title: "Shop by material",
      copy: "The feel changes everything.",
      items: [
        {
          title: "Silk",
          copy: "Lustrous & timeless",
          href: "/?route=material-silk",
          color: "#6b1c2b",
          media: {
            src: "/assets/design-material-silk.png",
            alt: "Deep garnet silk fabric folded in soft luminous pleats",
            tone: "rust",
            position: "center center",
          },
        },
        {
          title: "Chiffon",
          copy: "Light & airy · flowing grace",
          href: "/?route=material-chiffon",
          color: "#5b6337",
          media: {
            src: "/assets/design-material-chiffon.png",
            alt: "Blush and ivory chiffon fabric layered in airy translucent folds",
            tone: "paper",
            position: "center center",
          },
        },
        {
          title: "Organza",
          copy: "Sheer & luminous · pure sophistication",
          href: "/?route=material-organza",
          color: "#b7834d",
          media: {
            src: "/assets/design-material-organza.png",
            alt: "Luminous ivory organza fabric folded into crisp translucent layers",
            tone: "paper",
            position: "center center",
          },
        },
        {
          title: "Georgette",
          copy: "Soft drape · effortless beauty",
          href: "/?route=material-georgette",
          color: "#4f5969",
          media: {
            src: "/assets/design-material-georgette.png",
            alt: "Coral and marigold georgette fabric gathered into soft matte folds",
            tone: "ochre",
            position: "center center",
          },
        },
        {
          title: "Kota",
          copy: "Breezy & textured · made for ease",
          href: "/?route=material-kota",
          color: "#786a73",
          media: {
            src: "/assets/design-material-kota.png",
            alt: "Ivory and indigo Kota cotton fabric showing its airy square weave",
            tone: "indigo",
            position: "center center",
          },
        },
        {
          title: "Linen",
          copy: "Naturally relaxed · always in style",
          href: "/?route=material-linen",
          color: "#b8895b",
          media: {
            src: "/assets/design-material-linen.png",
            alt: "Natural oat and indigo linen fabric with a visible slubbed weave",
            tone: "indigo",
            position: "center center",
          },
        },
      ],
    },
    {
      id: "design-testimonials",
      number: "08",
      name: "Testimonials",
      type: "testimonials",
      hideReviewNotes: true,
      title: "Loved by her",
      copy: "Real drapes, real days — in her words.",
      items: [
        {
          name: "Ananya R.",
          quote: "The sage handblock drapes soft and sits through a full workday without fuss.",
          meta: "Bengaluru · Everyday",
          media: {
            src: "/assets/proof-1.jpg",
            alt: "Ananya wearing a sage handblock saree",
            tone: "moss",
            position: "center top",
          },
        },
        {
          name: "Meera K.",
          quote: "I wore the indigo print to a cousin's brunch — compliments before the first chai.",
          meta: "Mumbai · Festive",
          media: {
            src: "/assets/proof-2.jpg",
            alt: "Meera in an indigo printed saree",
            tone: "indigo",
            position: "center",
          },
        },
        {
          name: "Priya S.",
          quote: "Marigold borders that feel special, not costume. Exactly what I wanted for office Fridays.",
          meta: "Pune · Work",
          media: {
            src: "/assets/proof-3.jpg",
            alt: "Priya in a marigold border saree",
            tone: "ochre",
            position: "center top",
          },
        },
        {
          name: "Divya M.",
          quote: "Pre-stitched RTW got me out the door in five minutes — still looked like a proper drape.",
          meta: "Hyderabad · Ready-to-wear",
          media: {
            src: "/assets/product-sage.jpg",
            alt: "Divya in a sage ready-to-wear saree",
            tone: "moss",
            position: "center",
          },
        },
        {
          name: "Kavya N.",
          quote: "The indigo silk held its fall through the whole wedding weekend. Worth every rupee.",
          meta: "Chennai · Wedding",
          media: {
            src: "/assets/product-indigo.jpg",
            alt: "Kavya in an indigo silk saree",
            tone: "indigo",
            position: "center top",
          },
        },
        {
          name: "Sneha P.",
          quote: "Everyday cotton that doesn't look everyday. I've already ordered a second colour.",
          media: {
            src: "/assets/product-marigold.jpg",
            alt: "Sneha in a marigold cotton saree",
            tone: "ochre",
            position: "center",
          },
        },
        {
          name: "Ishita V.",
          quote: "Soft enough for school-run mornings, polished enough for evening plans.",
          meta: "Delhi · Everyday",
          media: {
            src: "/assets/occasion-everyday.jpg",
            alt: "Ishita in an everyday printed saree",
            tone: "paper",
            position: "center top",
          },
        },
        {
          name: "Riya T.",
          quote: "Festive without the weight — I danced till midnight and the pleats stayed put.",
          meta: "Kolkata · Festive",
          media: {
            src: "/assets/occasion-festive.jpg",
            alt: "Riya in a festive saree",
            tone: "rust",
            position: "center",
          },
        },
      ],
    },
    {
      id: "footer",
      number: "09",
      name: "Footer",
      type: "footer",
      annotation:
        "Close the trust loop with shipping, returns, COD, WhatsApp, care and contact details.",
      brand: "SAMANTHA FAB",
      brandLine: "Modern drapes, expressive prints and everyday ease.",
      columns: [
        {
          heading: "Shop",
          links: [
            { label: "New arrivals", href: "/?route=new-arrivals" },
            { label: "Sarees", href: "/?route=sarees" },
            { label: "Ready-to-wear", href: "/?route=ready-to-wear" },
            { label: "Sale", href: "/?route=sale" },
          ],
        },
        {
          heading: "Help",
          links: [
            { label: "Shipping", href: "/?route=shipping" },
            { label: "Returns", href: "/?route=returns" },
            { label: "COD", href: "/?route=cod" },
            { label: "Care guide", href: "/?route=care" },
          ],
        },
        {
          heading: "About",
          links: [
            { label: "Our story", href: "/?route=story" },
            { label: "Journal", href: "/?route=journal" },
            { label: "Contact", href: "/?route=contact" },
          ],
        },
        {
          heading: "Stay in touch",
          links: [
            { label: "Instagram", href: "/?route=instagram" },
            { label: "WhatsApp", href: "https://wa.me/" },
            { label: "Email", href: "mailto:hello@samanthafab.example" },
          ],
        },
      ],
      copyright: "© Samantha Fab. Playground concept.",
    },
  ],
};
