export const homepage = {
  key: "homepage",
  title: "Samantha Fab — Modern Indian Sarees",
  eyebrow: "Playground / Homepage concept",
  description:
    "Editorial fashion-commerce homepage experiment. Annotations appear only with ?notes=1.",
  sections: [
    {
      id: "utility-navigation",
      number: "00",
      name: "Utility + Navigation",
      type: "header",
      annotation:
        "Keep trust visible; simplify the route into Shop, Collections, Discover and Services. Sticky nav after the utility strip.",
      utility: ["COD across India", "Easy returns & exchange", "WhatsApp assistance"],
      brand: "SAMANTHA FAB",
      nav: [
        { label: "Shop", href: "/?route=shop" },
        { label: "Collections", href: "/?route=collections" },
        { label: "Discover", href: "/?route=discover" },
        { label: "Services", href: "/?route=services" },
      ],
      actions: [
        { label: "Search", href: "/?route=search", ariaLabel: "Search" },
        { label: "Account", href: "/?route=account", ariaLabel: "Account", className: "nav-action--account" },
        { label: "Bag (0)", href: "/?route=bag", ariaLabel: "Bag, 0 items" },
      ],
    },
    {
      id: "campaign-hero",
      number: "01",
      name: "Campaign Hero",
      type: "hero",
      annotation:
        "One visual world, one primary route and one secondary route. No sale message in the opening frame.",
      eyebrow: "New collection / Samantha Fab",
      title: "Sarees for the way you move.",
      copy: "Modern drapes, expressive prints, and effortless ways to wear them.",
      primaryAction: { label: "Shop the new edit", href: "/?route=new-edit" },
      secondaryAction: { label: "Find your saree", href: "/?route=find-saree" },
      media: {
        src: "./assets/hero-saree.jpg",
        alt: "Woman in a rose shimmer saree looking over her shoulder",
        tone: "indigo",
        position: "center top",
        note: "Concept stock photo — replace with Samantha Fab campaign photography.",
      },
    },
    {
      id: "shop-by-occasion",
      number: "02",
      name: "Shop by Occasion",
      type: "occasion",
      annotation:
        "Occasion is the first browse decision. Five editorial tiles with a shared baseline and hairline rules — not floating cards.",
      eyebrow: "Discover by occasion",
      title: "What are you dressing for?",
      copy: "Start with the moment, then find the saree.",
      items: [
        {
          title: "Everyday",
          href: "/?route=occasion-everyday",
          media: {
            src: "./assets/occasion-everyday.jpg",
            alt: "Woman in a purple saree with gold border",
            tone: "ochre",
            position: "center",
            note: "Occasion image: Everyday — replace with brand shoot.",
          },
        },
        {
          title: "Work",
          href: "/?route=occasion-work",
          media: {
            src: "./assets/occasion-work.jpg",
            alt: "Woman in a sage green silk saree",
            tone: "indigo",
            position: "center",
            note: "Occasion image: Work — replace with brand shoot.",
          },
        },
        {
          title: "Festive",
          href: "/?route=occasion-festive",
          media: {
            src: "./assets/occasion-festive.jpg",
            alt: "Woman in a cream and gold festive saree outdoors",
            tone: "rust",
            position: "center",
            note: "Occasion image: Festive — replace with brand shoot.",
          },
        },
        {
          title: "Wedding guest",
          href: "/?route=occasion-wedding-guest",
          media: {
            src: "./assets/occasion-wedding.jpg",
            alt: "Woman in a purple and gold wedding-guest saree",
            tone: "moss",
            position: "center",
            note: "Occasion image: Wedding guest — replace with brand shoot.",
          },
        },
        {
          title: "Ready-to-wear",
          href: "/?route=occasion-rtw",
          media: {
            src: "./assets/occasion-rtw.jpg",
            alt: "Woman wearing a ready-to-drape saree",
            tone: "paper",
            position: "center",
            note: "Occasion image: Ready-to-wear — replace with brand shoot.",
          },
        },
      ],
    },
    {
      id: "new-arrivals",
      number: "03",
      name: "New Arrivals",
      type: "products",
      annotation:
        "Keep the first product rail edited: four pieces, with fabric, price and one restrained NEW label.",
      eyebrow: "Just in",
      title: "The latest from Samantha.",
      copy: "A considered starting point for the collection.",
      viewAll: { label: "View all new arrivals", href: "/?route=new-arrivals" },
      products: [
        {
          name: "Sage green handblock saree",
          material: "Handblock cotton",
          price: "₹1,899",
          href: "/?route=product-sage-handblock",
          tag: "New",
          media: {
            src: "./assets/product-sage.jpg",
            alt: "Sage green silk saree with geometric weave",
            tone: "moss",
            position: "center",
            note: "Product stand-in — replace with Sage green handblock product shot.",
          },
        },
        {
          name: "Indigo stripe ready-to-wear",
          material: "Soft linen blend",
          price: "₹2,499",
          href: "/?route=product-indigo-rtw",
          media: {
            src: "./assets/product-indigo.jpg",
            alt: "Woman in a draped indigo-toned saree",
            tone: "indigo",
            position: "center",
            note: "Product stand-in — replace with Indigo stripe RTW product shot.",
          },
        },
        {
          name: "Marigold printed saree",
          material: "Lightweight georgette",
          price: "₹1,299",
          href: "/?route=product-marigold",
          media: {
            src: "./assets/product-marigold.jpg",
            alt: "Woman in a warm-toned printed saree",
            tone: "ochre",
            position: "center",
            note: "Product stand-in — replace with Marigold printed product shot.",
          },
        },
        {
          name: "Black border everyday saree",
          material: "Office-friendly cotton",
          price: "₹1,699",
          href: "/?route=product-black-border",
          media: {
            src: "./assets/product-black.jpg",
            alt: "Woman in a pink and black bordered saree",
            tone: "ink",
            position: "center",
            note: "Product stand-in — replace with Black border everyday product shot.",
          },
        },
      ],
    },
    {
      id: "ready-to-wear",
      number: "04",
      name: "Ready-to-Wear",
      type: "split",
      annotation:
        "Show the benefit in use. Numbered hairline list — no rounded copy card.",
      eyebrow: "Ready-to-wear",
      title: "A saree that keeps up.",
      copy: "Pre-stitched, lightweight, and made for days when getting dressed should feel simple.",
      points: ["Pre-stitched ease", "Comfortable movement", "Functional pocket detail"],
      action: { label: "Explore ready-to-wear", href: "/?route=ready-to-wear" },
      media: {
        src: "./assets/rtw-motion.jpg",
        alt: "Woman in a saree shown in a natural standing pose",
        tone: "moss",
        position: "center",
        note: "Concept stock — replace with RTW movement clip or draping still.",
      },
    },
    {
      id: "shop-by-price",
      number: "05",
      name: "Shop by Price",
      type: "price",
      annotation:
        "Exactly three equal panels. Large price typography as the visual anchor. No sale stickers.",
      eyebrow: "Shop by price",
      title: "Find your price point.",
      copy: "Three simple ways into the collection.",
      items: [
        {
          label: "Under",
          value: "₹999",
          href: "/?route=price-999",
          tone: "paper",
        },
        {
          label: "Under",
          value: "₹1,999",
          href: "/?route=price-1999",
          tone: "moss",
        },
        {
          label: "Under",
          value: "₹2,999",
          href: "/?route=price-2999",
          tone: "ochre",
        },
      ],
    },
    {
      id: "why-samantha",
      number: "06",
      name: "Why Samantha Exists",
      type: "story",
      annotation:
        "One focused editorial story. Quieter than the hero. No mission/vision/values collage.",
      eyebrow: "Why Samantha exists",
      title: "Tradition without standing still.",
      copy:
        "Regional inspiration, expressive prints, soft fabrics, and modern drapes — made for how women actually move through their day.",
      action: { label: "Read our story", href: "/?route=story" },
      media: {
        src: "./assets/story-craft.jpg",
        alt: "Woman in a cream printed saree with a modern plum blouse",
        tone: "rust",
        position: "center",
        note: "Concept stock — replace with craft, textile, or founder imagery.",
      },
      caption: "Printed cotton drape · modern blouse pairing",
      captionPlaceholder: false,
    },
    {
      id: "made-for-real-life",
      number: "07",
      name: "Made for Real Life",
      type: "benefits",
      annotation:
        "Magazine information spread: large numbers, concise explanations, hairline dividers. No icon cards.",
      eyebrow: "Made for real life",
      title: "Why she will reach for it again.",
      features: [
        {
          title: "Easy to wear",
          copy: "Clear drapes and thoughtful construction so getting ready stays simple.",
        },
        {
          title: "Lightweight fabrics",
          copy: "Cottons, georgettes, and soft blends that stay comfortable through the day.",
        },
        {
          title: "Room to move",
          copy: "Cut and fall that keep up with commuting, work, and evening plans.",
        },
        {
          title: "Day-to-evening",
          copy: "Looks that shift from desk to dinner without a full change.",
        },
      ],
    },
    {
      id: "worn-by-real-women",
      number: "08",
      name: "Worn by Real Women",
      type: "proof",
      annotation:
        "Human proof without fake star ratings. Quotes link to products. Fallback panels are not claimed as customers.",
      eyebrow: "Worn by real women",
      title: "Seen on her. Made for you.",
      items: [
        {
          quote: "The easiest saree I have worn.",
          caption: "Concept imagery · replace with product-linked UGC",
          captionPlaceholder: true,
          href: "/?route=product-sage-handblock",
          feature: true,
          media: {
            src: "./assets/proof-1.jpg",
            alt: "Woman wearing a rose saree",
            tone: "rust",
            position: "center top",
            note: "Not a verified customer photo — replace with real UGC.",
          },
        },
        {
          quote: "It works for my office and dinner plans.",
          caption: "Concept imagery · product-linked review pending",
          captionPlaceholder: true,
          href: "/?route=product-indigo-rtw",
          media: {
            src: "./assets/proof-2.jpg",
            alt: "Smiling woman in a white and red bordered saree",
            tone: "indigo",
            position: "center",
            note: "Not a verified customer photo — replace with real UGC.",
          },
        },
        {
          quote: "The colour looks even better in person.",
          caption: "Concept imagery · product-linked review pending",
          captionPlaceholder: true,
          href: "/?route=product-marigold",
          media: {
            src: "./assets/proof-3.jpg",
            alt: "Woman in a pink silk saree",
            tone: "ochre",
            position: "center",
            note: "Not a verified customer photo — replace with real UGC.",
          },
        },
      ],
    },
    {
      id: "stylist-service",
      number: "09",
      name: "Ask a Stylist / Design Your Dream",
      type: "service",
      annotation:
        "Assisted commerce as a service invitation — one filled CTA and one text link. Keep spacing tight and intentional; no quiz or chat simulation.",
      eyebrow: "Need a second opinion?",
      title: "Tell us the occasion. We will help with the saree.",
      copy: "A direct human route for colour, fit, styling, or custom design questions.",
      primaryAction: {
        label: "Ask a stylist on WhatsApp",
        href: "https://wa.me/",
      },
      secondaryAction: {
        label: "Design your dream saree",
        href: "/?route=design-your-dream",
      },
      media: {
        src: "./assets/service-textile.jpg",
        alt: "Detail of a pink silk saree drape",
        tone: "moss",
        position: "center",
        note: "Concept stock — optional textile or stylist imagery.",
      },
    },
    {
      id: "last-chance",
      number: "10",
      name: "Last Chance / Sale",
      type: "sale",
      annotation:
        "Sale stays late. Show a short product rail of last pieces with clear prices — no countdown or discount stickers.",
      eyebrow: "Last chance",
      title: "Worth finding. Last pieces, special prices.",
      actions: [
        { label: "Shop last chance", href: "/?route=sale" },
        { label: "Shop under ₹999", href: "/?route=price-999" },
      ],
      products: [
        {
          name: "Indigo stripe ready-to-wear",
          material: "Soft linen blend",
          compareAt: "₹2,499",
          price: "₹1,799",
          href: "/?route=sale-indigo-rtw",
          tag: "Last pieces",
          media: {
            src: "./assets/product-indigo.jpg",
            alt: "Indigo stripe ready-to-wear saree on sale",
            tone: "indigo",
            position: "center",
            note: "Sale product stand-in.",
          },
        },
        {
          name: "Marigold printed saree",
          material: "Lightweight georgette",
          compareAt: "₹1,299",
          price: "₹899",
          href: "/?route=sale-marigold",
          tag: "Last pieces",
          media: {
            src: "./assets/product-marigold.jpg",
            alt: "Marigold printed saree on sale",
            tone: "ochre",
            position: "center",
            note: "Sale product stand-in.",
          },
        },
        {
          name: "Black border everyday saree",
          material: "Office-friendly cotton",
          compareAt: "₹1,699",
          price: "₹1,199",
          href: "/?route=sale-black-border",
          tag: "Last pieces",
          media: {
            src: "./assets/product-black.jpg",
            alt: "Black border everyday saree on sale",
            tone: "ink",
            position: "center",
            note: "Sale product stand-in.",
          },
        },
        {
          name: "Sage green handblock saree",
          material: "Handblock cotton",
          compareAt: "₹1,899",
          price: "₹1,299",
          href: "/?route=sale-sage-handblock",
          tag: "Last pieces",
          media: {
            src: "./assets/product-sage.jpg",
            alt: "Sage green handblock saree on sale",
            tone: "moss",
            position: "center",
            note: "Sale product stand-in.",
          },
        },
      ],
    },
    {
      id: "saree-library",
      number: "11",
      name: "Saree Library",
      type: "library",
      annotation:
        "Guides are available but de-emphasised — a quiet link strip before the footer, not a major content block.",
      eyebrow: "Guides",
      title: "A little help before you choose.",
      items: [
        { title: "Choose your fabric", href: "/?route=guide-fabric" },
        { title: "Find your drape", href: "/?route=guide-drape" },
        { title: "Pair your blouse", href: "/?route=guide-blouse" },
      ],
    },
    {
      id: "footer",
      number: "12",
      name: "Footer",
      type: "footer",
      annotation:
        "Close the trust loop with shipping, returns, COD, WhatsApp, care and contact details.",
      brand: "SAMANTHA FAB",
      brandLine: "Modern drapes, expressive prints and everyday ease.",
      columns: [
        {
          heading: "Shop",
          links: [
            { label: "New arrivals", href: "/?route=new-arrivals" },
            { label: "Sarees", href: "/?route=sarees" },
            { label: "Ready-to-wear", href: "/?route=ready-to-wear" },
            { label: "Bestsellers", href: "/?route=bestsellers" },
            { label: "Best on budget", href: "/?route=shop-under" },
            { label: "Sale", href: "/?route=sale" },
            { label: "Clearance", href: "/?route=clearance" },
          ],
        },
        {
          heading: "Help",
          links: [
            { label: "Shipping", href: "/?route=shipping" },
            { label: "Returns & exchanges", href: "/?route=returns" },
            { label: "COD", href: "/?route=cod" },
            { label: "Track order", href: "/?route=track-order" },
            { label: "Size guide", href: "/?route=size-guide" },
            { label: "Care guide", href: "/?route=care" },
          ],
        },
        {
          heading: "About",
          links: [
            { label: "Our story", href: "/?route=story" },
            { label: "Journal", href: "/?route=journal" },
            { label: "Stores", href: "/?route=stores" },
            { label: "Contact", href: "/?route=contact" },
            { label: "Privacy", href: "/?route=privacy" },
            { label: "Terms", href: "/?route=terms" },
          ],
        },
        {
          heading: "Stay in touch",
          links: [
            { label: "Instagram", href: "/?route=instagram" },
            { label: "WhatsApp", href: "https://wa.me/" },
            { label: "Email", href: "mailto:hello@samanthafab.example" },
            { label: "Newsletter", href: "/?route=newsletter" },
          ],
        },
      ],
      trust: [
        { icon: "cod", label: "Cash on delivery" },
        { icon: "returns", label: "Easy returns" },
        { icon: "shipping", label: "Pan-India shipping" },
        { icon: "whatsapp", label: "WhatsApp support" },
      ],
      copyright: "© Samantha Fab. Playground concept.",
    },
  ],
};
